### ISSUE TITLE
[Feature request] Notification => no reload

### ISSUE THREAD

**Issue by DasLampe** [strackoverflow/phnx#11]
Hey,

yesterday, my Palm Pre had a phnx notification because new DM.
When i tap on this message, open phnx and phnx load the messages.

Why phnx load the messages 2 times?
I think, you can cache the messages, which loaded for notification. So you doesn't need a new reload and phnx is faster, after notifications.

**Comment by strackoverflow** [comment]
This was the original intention but if I recall correctly it would have required lots of extra work to get the "New Tweets" indicator to work with it. Also, all of the timelines need to refresh on app load anyway since notifications check only every 15 min or so, so new mentions/messages may have come in the meantime, which would then move the "New Tweets" indicator above the existing "new" tweet, causing confusion. I would love to reduce service calls as much as possible, but I don't think this is the place.
